name: dashboards
channels:
  - conda-forge
  - defaults
dependencies:
  - voila
  - widgetsnbextension
  - ipykernel
  - ipywidgets
  - jupyterlab
  - altair
  - ipykernel
  - nodejs=12
  - matplotlib
  - ipysheet
  - pip
  - bash_kernel
  - bqplot
#  - pip:
#    - bqplot


  
