name: dashboards
channels:
  - conda-forge
  - defaults
dependencies:
  - voila=0.1.10
  - widgetsnbextension
  # Python Kernel
  - ipykernel
  - ipywidgets
  - jupyterlab
  - altair
  - ipykernel
  - nodejs=12
  - matplotlib
  - ipysheet
  - pip
  - pip:
    - ipymaterialui
    - bqplot
    - ipyvuetify
    - voila-vuetify

  